name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Listar arquivos no repositório
      run: ls -la

    - name: Executar script com token do segredo
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
      run: |
        echo "Verificando o token..."
        if [ -z "$GITHUB_TOKEN" ]; then
          echo "Token não encontrado!"
          exit 1
        fi
        echo "Executando script.js..."
        node script.js
