name: Fetch GitHub Repositories

on:
  workflow_dispatch: # Permite disparar manualmente a ação

jobs:
  fetch-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Enviar requisição à API do GitHub
        env:
          PERSONAL_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
        run: |
          echo "Buscando repositórios do GitHub..."
          curl -H "Authorization: Bearer $PERSONAL_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/users/${{ github.actor }}/repos > repos.json

      - name: Exibir os repositórios (opcional)
        run: |
          echo "Repositórios obtidos:"
          cat repos.json
